config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :users, only: [:edit, :update]
  resources :posts, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
  end

  def show
    @post = Post.find(params[:id])
  end  

  private
  def post_params
    params.require(:post).permit(:name, :image, :text, :outer, :base, :inner, :accessory, :hairstyle)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title PashariApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_footer.html.haml
.footer
  （C）SEGA PHANTASY STAR ONLINE 2

app/views/posts/_header.html.haml
.header
  .header__box
    .header__box__upper
      = link_to root_path do
        = image_tag "pasharirogo.jpg", class: "header__box__upper__text"
      .header__box__upper__search
        %form.header__box__upper__search__form
          %input{type: "text", placeholder: "キーワードから探す", class: "header__box__upper__search__form__input"}
          %button{type: "submit", class: "header__box__upper__search__form__btn"}
            = image_tag "icon-search 1.png", class: "header__box__upper__search__form__btn__icon"
    .header__box__lawer
      %ul.header__box__lawer__left
        %li.header__box__lawer__left__category
          = link_to "さっそく投稿する", new_post_path, class: "header__box__lawer__left__category__btn"
      %ul.header__box__lawer__right
        - if user_signed_in?
          %li.header__box__lawer__right__login
            = link_to destroy_user_session_path, method: :delete, class: "header__box__lawer__right__login__btn" do
              ログアウト
          %li.header__box__lawer__right__sign-up
            = link_to "#", class: "header__box__lawer__right__sign-up__btn" do
              マイページ
        - else
          %li.header__box__lawer__right__login
            = link_to new_user_session_path, class: "header__box__lawer__right__login__btn" do
              ログイン
          %li.header__box__lawer__right__sign-up
            = link_to "#", class: "header__box__lawer__right__sign-up__btn" do
              新規登録

app/views/posts/_main.html.haml
.main
  .main__upper
    .main__upper__contents
      .main__upper__contents__title
        SS投稿アプリ
      .main__upper__contents__text
        お気に入りのマイファッションをみんなに自慢しよう！
  .main__lower
    .main__lower__title
      SS一覧
    .main__lower__contents
      .main__lower__contents__title
        新着投稿SS！！
      .main__lower__contents__lists
        .main__lower__contents__lists__list
          = link_to "#" do
            .main__lower__contents__lists__list__image
              = image_tag "rappi1.jpg", class: "item-image"
            .main__lower__contents__lists__list__box
              .main__lower__contents__lists__list__box__name
                題名
              .main__lower__contents__lists__list__box__details
                %ul.main__lower__contents__lists__list__box__details__box
                  %li.main__lower__contents__lists__list__box__details__box__user
                    投稿者
                  %li.main__lower__contents__lists__list__box__details__box__like
                    %i.fa.fa-heart
                    %p.like-number &nbsp;2
        -# サーバーサイド実装まで仮
        .main__lower__contents__lists__list
          = link_to "#" do
            .main__lower__contents__lists__list__image
              = image_tag "rappi2.jpg", class: "item-image"
            .main__lower__contents__lists__list__box
              .main__lower__contents__lists__list__box__name
                題名
              .main__lower__contents__lists__list__box__details
                %ul.main__lower__contents__lists__list__box__details__box
                  %li.main__lower__contents__lists__list__box__details__box__user
                    投稿者
                  %li.main__lower__contents__lists__list__box__details__box__like
                    %i.fa.fa-heart
                    %p.like-number &nbsp;0
        .main__lower__contents__lists__list
          = link_to "#" do
            .main__lower__contents__lists__list__image
              = image_tag "rappi3.jpg", class: "item-image"
            .main__lower__contents__lists__list__box
              .main__lower__contents__lists__list__box__name
                題名
              .main__lower__contents__lists__list__box__details
                %ul.main__lower__contents__lists__list__box__details__box
                  %li.main__lower__contents__lists__list__box__details__box__user
                    投稿者
                  %li.main__lower__contents__lists__list__box__details__box__like
                    %i.fa.fa-heart
                    %p.like-number &nbsp;4
        .main__lower__contents__lists__list
          = link_to "#" do
            .main__lower__contents__lists__list__image
              = image_tag "rappi4.jpg", class: "item-image"
            .main__lower__contents__lists__list__box
              .main__lower__contents__lists__list__box__name
                題名
              .main__lower__contents__lists__list__box__details
                %ul.main__lower__contents__lists__list__box__details__box
                  %li.main__lower__contents__lists__list__box__details__box__user
                    投稿者
                  %li.main__lower__contents__lists__list__box__details__box__like
                    %i.fa.fa-heart
                    %p.like-number &nbsp;0

app/views/posts/_sub-header.html.haml
.sub__header
  = link_to root_path do
    = image_tag "pasharirogo.jpg", class: "header__sub-page"

app/views/posts/create.html.haml
.done#fullsize
  .done__title
    投稿が完了しました！
  .done__backlink
    = link_to 'トップページへ戻る', root_path, class: 'link'
  .done__backlink
    = link_to '投稿した商品を確認する', post_path(@post), class: 'link'

app/views/posts/index.html.haml
.wrapper
  - @posts.each do |post|
    = link_to post_path(post) do
      = post.name
  = render "header"
  = render "main"
  = render "footer"

app/views/posts/new.html.haml
.post
  -# ヘッダー
  = render 'sub-header'

  -# メイン
  .contents
    .container
      = form_with(model: @post, local: true) do |form|
        .container__upper
          %h3.container__upper__head ファッション情報を入力してください
        -# Title部分
        .container__main
          .container__main__group
            .container__main__group__name
              %label
                Title
                %span.form-require
                  必須
              %div
                = form.text_field :name, class: "container__main__group__input", placeholder: "Title"
        -# 画像投稿部分
        .container__main
          .container__main__group
            .container__main__group__form
              %label
                画像
                %span.form-require
                  必須
              %div
                = form.text_field :image, class: "container__main__group__input", placeholder: "Image Url"
        -# PR説明部分
        .container__main
          .container__main__group
            .container__main__group__form
              %label
                PRポイント
                %span.form-require
                  必須
              %div
                = form.text_area :text, class: "container__main__group__input", placeholder: "PRポイントを書いてみよう！" , rows: "10"
        -# アウター部分
        .container__main
          .container__main__group
            .container__main__group__form
              %label
                アウターウェア
                %span.form-require
                  必須
              %div
                = form.text_field :outer, class: "container__main__group__input", placeholder: "アウターウェア"
        -# ベースウェア部分
        .container__main
          .container__main__group
            .container__main__group__form
              %label
                ベースウェア
                %span.form-require
                  必須
              %div
                = form.text_field :base, class: "container__main__group__input", placeholder: "ベースウェア"
        -# インナーウェア部分
        .container__main
          .container__main__group
            .container__main__group__form
              %label
                インナーウェア
                %span.form-require
                  必須
              %div
                = form.text_field :inner, class: "container__main__group__input", placeholder: "インナーウェア"
        -# アクセサリー部分
        .container__main
          .container__main__group
            .container__main__group__form
              %label
                アクセサリー
              %div
                = form.text_field :accessory, class: "container__main__group__input", placeholder: "アクセサリー"
        -# ヘアスタイル部分
        .container__main
          .container__main__group
            .container__main__group__form
              %label
                ヘアスタイル
                %span.form-require
                  必須
              %div
                = form.text_field :hairstyle, class: "container__main__group__input", placeholder: "ヘアスタイル"
        -# SENDボタン部分
        .container__btn
          = form.submit "SEND", class: "container__btn__confirm"
        -# 戻るボタン部分
        .container__back
          = link_to "トップページに戻る", "/", class:'container__back__btn'
  -# フッター
  = render 'footer'

app/views/posts/show.html.haml
-# ヘッダー
= render 'sub-header'

-# ファッション情報
.main
  .main__show
    .main__show__title
      .main__show__title__content
        title
        .main__show__title__content__text
          = @post.name
    .main__show__contents
      .main__show__contents__content
        text
        .main__show__contents__content__text
          = @post.text
    .main__show__upper
      .main__show__contents__content
        画像表示
        .main__show__contents__content__img
          = @post.image
    .main__show__lower
      .main__show__lower__head
        .main__show__lower__head__content
          ヘアスタイル
          .main__show__lower__head__content__text
            = @post.hairstyle
      .main__show__lower__wear
        .main__show__lower__wear__content
          ウェア系
      .main__show__lower__accessory
        .main__show__lower__accessory__content
          アクセ










-# フッター
= render 'footer'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", '#', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'